# Generated by Django 2.2.1 on 2019-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_area', models.FloatField()),
                ('average_volume', models.FloatField()),
                ('total_boxes', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_conditions',
            },
        ),
        migrations.AlterField(
            model_name='box',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
