# Generated by Django 2.2.1 on 2019-05-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190526_1350'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventoryconditions',
            table='inventory_condition',
        ),
    ]
